name: Java auto build with Gradle

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build both distributable jars
        run: ./gradlew clean :BungeeSK:shadowJar :VelocitySK:shadowJar --no-daemon
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BungeeSK
          path: |
            BungeeSK/build/libs/BungeeSK.jar
            VelocitySK/build/libs/BungeeSK-Velocity.jar
